[package]

name = "lyon_svg"
version = "0.2.0"
description = "[TODO] High-level SVG rendering library on top of lyon's tesselator."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_svg"
path = "src/lib.rs"

[dependencies]

lyon_tessellation = { version = "0.2.0", path = "../tessellation" }
lyon_core = { version = "0.2.0", path = "../core" }
lyon_extra = { version = "0.2.0", path = "../extra" }
