[package]
name = "lyon_path"
version = "0.1.1"
description = "Utilities to build vector paths."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_path"

[dependencies]
lyon_core = { version = "0.1.1", path = "../core" }
lyon_bezier = { version = "0.1.1", path = "../bezier" }
lyon_path_builder = { version = "0.1.1", path = "../path_builder" }
lyon_path_iterator = { version = "0.1.1", path = "../path_iterator" }
