[package]

name = "io"
version = "0.1.0"
authors = [
    "Nicolas Silva <nical.silva@gmail.com>",
]

[[lib]]
name = "io"
path = "./lib.rs"

[dependencies.data]
path = "../data/"

[dependencies.gfx2d]
path = "../gfx2d/"
