[package]

name = "lyon"
version = "0.0.3"
description = "2D Graphics rendering experiments."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon"
path = "src/lib.rs"

[dependencies]

lyon_tesselation = { version = "0.0.3", path = "tesselation/" }
lyon_svg = { version = "0.0.3", path = "svg/" }
lyon_core = { version = "0.0.3", path = "core/" }
lyon_extra = { version = "0.0.3", path = "extra/" }
