[package]

name = "lyon"
version = "0.1.1"
description = "2D Graphics rendering experiments."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon"
path = "src/lib.rs"

[dependencies]

lyon_tessellation = { version = "0.1.1", path = "tessellation/" }
lyon_svg = { version = "0.1.1", path = "svg/" }
lyon_core = { version = "0.1.1", path = "core/" }
lyon_bezier = { version = "0.1.1", path = "bezier/" }
lyon_path = { version = "0.1.1", path = "path/" }
lyon_path_builder = { version = "0.1.1", path = "path_builder/" }
lyon_path_iterator = { version = "0.1.1", path = "path_iterator/" }
lyon_extra = { version = "0.1.1", path = "extra/" }
