[package]

name = "lyon"
version = "0.0.1"
description = "2D Graphics rendering experiments."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/vodk.rs"
license = "MIT/Apache-2.0"

[lib]
name = "lyon"
path = "src/lib.rs"

[dependencies]

sid = { version = "0.1.0", path = "../vodk/id/sid" }
sid_vec = { version = "0.1.0", path = "../vodk/id/sid_vec" }
vodk_math = { version = "0.0.3", path = "../vodk/math/" }
