[package]

name = "lyon"
version = "0.0.1"
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
license = "MIT/Apache-2.0"

[lib]
name = "lyon"
path = "src/lib.rs"

[dependencies.vodk_alloc]
path = "../alloc/"

[dependencies.vodk_id]
path = "../id/"

[dependencies.vodk_math]
path = "../math/"
