[package]

name = "geom"
version = "0.0.1"
authors = [ "Nicolas Silva <nical@fastmail.com>" ]

[lib]
name = "geom"
path = "src/lib.rs"

[dependencies.vodk_alloc]
path = "../alloc/"

[dependencies.vodk_data]
path = "../data/"

[dependencies.vodk_math]
path = "../math/"

[dependencies.vodk_id]
path = "../id/"

[dependencies.euclid]
path = "../../euclid"
features = ["rustc_stable"]
