[package]

name = "lyon_extra"
version = "0.1.1"
description = "Various optional utilities for the lyon crate."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_extra"
path = "src/lib.rs"

[dependencies]

sid = { version = "0.1.0" }
sid_vec = { version = "0.1.0" }

lyon_core = { version = "0.1.1", path = "../core" }
