[package]
name = "lyon_svg_renderer"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]

[[bin]]
name = "renderer"
path = "src/svg_renderer.rs"

[dependencies]
lyon = { path = "../../" }
lyon_svg = { path = "../../svg" }
svgparser = "0.0.3"
gfx = "0.12.1"
glutin = "0.6.1"
gfx_window_glutin = "0.12.0"
rayon = "0.4.2"
clap = "2.13.0"
