[package]
name = "gpu_triangle_test"
version = "0.0.1"
authors = ["Nicolas Silva <nical.silva@gmail.com>"]

[[bin]]
name = "triangle_test"
path = "./main.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.data]
path = "../../../data/"

[dependencies.gpu]
path = "../../../gpu/"

