[package]

name = "sid_vec"
version = "0.1.0"
license = "MIT/Apache-2.0"
description = "Vector and slice indexed with strongly typed handles instead of usize."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/vodk.rs"
include = [ "Cargo.toml", "src/*.rs" ]

[lib]

name = "sid_vec"
path = "src/lib.rs"

[dependencies]

sid = { version = "0.1.0", path = "../sid" }
