[package]

name = "lyon_core"
version = "0.2.0"
description = "Common resources to all lyon crates."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_core"

[dependencies]
euclid = "0.10.1"