[package]
name = "gpu_cube_example"
version = "0.0.1"
authors = ["Nicolas Silva <nical@fastmail.com>"]

[[bin]]
name = "cube_example"
path = "./cube_example.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.vodk_data]
path = "../../data/"

[dependencies.vodk_math]
path = "../../math/"

[dependencies.vodk_gpu]
path = "../../gpu/"
    