[package]

name = "gfx2d"
version = "0.1.0"
authors = [
    "Nicolas Silva <nical.silva@gmail.com>",
]

[lib]
name = "gfx2d"
path = "./lib.rs"

[dependencies.vodk_data]
path = "../data/"

[dependencies.vodk_math]
path = "../math/"


