[package]
name = "Glium viewer"
version = "0.0.3"
authors = ["Nicolas Silva <nical@fastmail.com>"]

[[bin]]
name = "glium_tess_example"
path = "src/glium_tess_example.rs"

[dependencies]
lyon = { path = "../../" }

glutin = "0.6.1"
glium = "0.15.0"
