[package]

name = "sid_veclist"
version = "0.1.0"
description = "Simple Id. A tiny library providing strongly typed handles."
license = "MIT/Apache-2.0"
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/vodk.rs"
include = [ "Cargo.toml", "src/*.rs" ]

[lib]

name = "sid_veclist"
path = "src/lib.rs"

[dependencies]

sid = { version = "0.1.0", path = "../sid" }
