[package]

name = "lyon_tessellation"
version = "0.1.1"
description = "A low level path tessellation library."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_tessellation"
path = "src/lib.rs"

[dependencies]

lyon_core = { version = "0.1.1", path = "../core" }
lyon_extra = { version = "0.1.1", path = "../extra" }

sid = { version = "0.1.0" }
sid_vec = { version = "0.1.0" }
