[package]

name = "lyon_tessellation"
version = "0.3.2"
description = "A low level path tessellation library."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_tessellation"
path = "src/lib.rs"

[dependencies]

lyon_core = { version = "0.3.2", path = "../core" }
lyon_path = { version = "0.3.2", path = "../path" }
lyon_path_builder = { version = "0.3.2", path = "../path_builder" }
lyon_path_iterator = { version = "0.3.2", path = "../path_iterator" }

[dev-dependencies]
lyon_extra = { version = "0.3.2", path = "../extra" }
